# Generated by Django 4.0.4 on 2022-06-28 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('MBID', models.CharField(max_length=100)),
                ('spotify_uri', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetlistCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spotify_uri', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.artist')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.setlistcache')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='setlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.setlistcache'),
        ),
    ]
