# Generated by Django 4.0.4 on 2022-06-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_artist_mbid_alter_artist_spotify_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='setlist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.setlistcache'),
        ),
    ]
