# Generated by Django 4.0.4 on 2022-06-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_artist_setlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='setlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.setlistcache'),
        ),
    ]
