# Generated by Django 4.0.4 on 2022-06-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_artist_setlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='setlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.setlistcache'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_uri',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
